### ISSUE TITLE
Openshift 3.3 Deployment

### ISSUE THREAD

**Issue by ghost** [aaossa/flask-openshift#1]
Is this application hosted on Openshift 3 or later?

And if not then could you please help me to identify the directory structure for the Flask application to be deployed on Openshift 3.

**Comment by aaossa** [comment]
I'm sorry @open1312 , but this project was not meant to be used with OpenShift 3.x. The directory structure of the Flask app depends of the size of your app. Is your application big? Maybe you could use something like this:

```
run.py
Application
    __init__.py
    folder
        file.py
    another.py
```

**Comment by ghost** [comment]
Thanks for the prompt reply. Actually its a simple HTML5 website with no backend data. So do you have any idea how should a directory structure look like for Flask in Openshift 3.x

**Comment by aaossa** [comment]
You could use the structure from [this OpenShift demo repository](https://github.com/OpenShiftDemos/os-sample-python), and given that it seems like you want a static page you could use [a package-like structure](http://exploreflask.com/en/latest/organizing.html#package). I prefer this structure because all of the application files are together in the same folder, and the app (package) is at the same level that the server files (.s2i folder, for instance).

Hope this works for you :grin:
